[package]
name = "deltafusion"
version = "0.1.0"
edition = "2021"

[dependencies]
arrow = "27.0.0"
tokio = { version = "1.11.0", features = ["full"] }
deltalake = { version = "0.4.0", features = ["datafusion-ext"] }
